
# Loader Metadata
modLoader="javafml"
loaderVersion="[31,)"
#issueTrackerURL="" # optional

# Mods
[[mods]]
    modId="notreepunching"
    version="${file.jarVersion}"
    displayName="No Tree Punching"

    #updateJSONURL="http://myurl.me/" # optional
    #displayURL="http://example.com/" # optional
    #logoFile="examplemod.png" # optional
    #credits="" # optional
    authors="AlcatrazEscapee" # optional
    # The description text for the mod (multi line!)
    description='''
    This is a minecraft mod meant to add a little more believability to your first few minutes of minecraft play. It was initially inspired by features from TerraFirmaCraft, but has since been refocused around the titular idea: Blocks don't drop anything if broken with the incorrect tool.
    '''

# Dependencies
[[dependencies.notreepunching]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.notreepunching]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.notreepunching]]
    modId="alcatrazcore"
    mandatory=true
    versionRange="[2.0.0,)"
    ordering="NONE"
    side="BOTH"
